### ISSUE TITLE
Feature Request: Make solc install path configurable

### ISSUE THREAD

**Issue by MatthiasLohr** [iamdefinitelyahuman/py-solc-x#38]
# Version Info

* `py-solc-x` Version: 0.7.2
* OS: linux

## The Issue
 Hey,

thank you for your great work!

Could you please provide an optional parameter and some settings to specify in which the solc binaries should be installed? Thanks!

Best regards
Matthias

**Comment by iamdefinitelyahuman** [comment]
Yeah, that should be fairly easily implemented. Off the top of my head:

* Check for an environment variable `SOLCX_BINARY_PATH` and if found, use it instead of the default `~/.solcx`
* Add an `install_path` kwarg to `solcx.install_solc`, so individual projects can take control of where binaries are installed

Do you have a specific use case? Would one of these approaches work for you?

**Comment by MatthiasLohr** [comment]
Thank you for your quick reply!

Yeah that would work. I have an idea how to implement that, give me some time for providing a pull request.

**Comment by iamdefinitelyahuman** [comment]
I'm think that the environment variable should take precedence over the `install_path` kwarg. If a user really wants to install in a specific spot, they should be able to do so regardless.

Thanks in advance for doing the heavy lifting in the PR :)

**Comment by MatthiasLohr** [comment]
See #39.
